// Shim que re-exporta ícones do Tabler com os nomes usados pelo app.
// Trocar de biblioteca no futuro? só editar este arquivo.
export {
  TbArrowDown as ArrowDown,
  TbArrowRight as ArrowRight,
  TbArrowUp as ArrowUp,
  TbMeat as Beef,
  TbBell as Bell,
  TbCheck as Check,
  TbChevronLeft as ChevronLeft,
  TbChevronRight as ChevronRight,
  TbCircle as Circle,
  TbClock as Clock,
  TbCrown as Crown,
  TbDroplet as Droplet,
  TbBarbell as Dumbbell,
  TbFlame as Flame,
  TbHeart as Heart,
  TbHome as Home,
  TbChartLine as LineChart,
  TbListCheck as ListChecks,
  TbLoader2 as Loader2,
  TbLock as Lock,
  TbMedal as Medal,
  TbMessageCircle as MessageCircle,
  TbMoon as Moon,
  TbDots as MoreHorizontal,
  TbPlayerPause as Pause,
  TbPlayerPlay as Play,
  TbPlus as Plus,
  TbRefresh as RefreshCcw,
  TbSend as Send,
  TbSun as Sun,
  TbTarget as Target,
  TbTrophy as Trophy,
  TbUser as User,
  TbUsers as Users,
  TbToolsKitchen2 as Utensils,
  TbToolsKitchen as UtensilsCrossed,
  TbWeight as Weight,
  TbX as X,
  // Ícones de refeição (Diet ClassBadge)
  TbCoffee as Coffee,
  TbApple as Apple,
  TbSoup as Soup,
  TbCookie as Cookie,
  TbStar as Star,
} from 'react-icons/tb'
