// src/screens/Diet/dietMock.js

export const initialDietState = {
  daySummary: {
    kcal:   { goal: 2400 },
    macros: {
      protein: { goal: 150 },
      carbs:   { goal: 300 },
      fat:     { goal: 80 },
    },
  },
  water: { ml: 1000, goalMl: 2000, streak: 3 },
  classes: [
    {
      id: 'breakfast',
      name: 'Café da manhã',
      shortName: 'Café',
      goal: { kcal: 500, protein: 25 },
      streak: 12,
      state: 'open',
      items: [
        { id: 'b1',  name: 'Ovos',                    imageUrl: '/images/foods/ovos-mexidos.webp',            portion: '2 unidades', kcal: 140, protein: 12, checked: false, alternatives: [
          { id: 'b1a', name: 'Omelete', imageUrl: '/images/foods/omelete.webp', portion: '1 unidade', kcal: 150, protein: 12 },
        ]},
        { id: 'b2',  name: 'Pão francês',             imageUrl: '/images/foods/pao.webp',                     portion: '1 unidade',  kcal: 140, protein: 4,  checked: false, alternatives: [] },
        { id: 'b3',  name: 'Aveia',                   imageUrl: '/images/foods/mingal-de-aveia.webp',         portion: '3 col. sopa', kcal: 110, protein: 4, checked: false, alternatives: [] },
        { id: 'b4',  name: 'Iogurte natural',         imageUrl: '/images/foods/iogurte.webp',                 portion: '1 copo',     kcal: 90,  protein: 8,  checked: false, alternatives: [] },
        { id: 'b5',  name: 'Banana',                  imageUrl: '/images/foods/banana.webp',                  portion: '1 unidade',  kcal: 90,  protein: 1,  checked: false, alternatives: [] },
        { id: 'b6',  name: 'Café com leite',          imageUrl: '/images/foods/cafe-com-leite.webp',          portion: '1 xícara',   kcal: 60,  protein: 3,  checked: false, alternatives: [] },
        { id: 'b7',  name: 'Tapioca',                 imageUrl: '/images/foods/tapioca.webp',                 portion: '1 unidade',  kcal: 150, protein: 2,  checked: false, alternatives: [] },
        { id: 'b8',  name: 'Queijo branco',           imageUrl: '/images/foods/queijo-branco.webp',           portion: '2 fatias',   kcal: 100, protein: 8,  checked: false, alternatives: [] },
        { id: 'b9',  name: 'Suco de laranja natural', imageUrl: '/images/foods/suco-de-laranja.webp',         portion: '1 copo',     kcal: 110, protein: 2,  checked: false, alternatives: [] },
        { id: 'b10', name: 'Cuscuz',                  imageUrl: '/images/foods/cuscuz.webp',                  portion: '1 fatia',    kcal: 130, protein: 3,  checked: false, alternatives: [] },
      ],
    },
    {
      id: 'lunch',
      name: 'Almoço',
      shortName: 'Almoço',
      goal: { kcal: 800, protein: 45 },
      streak: 10,
      state: 'open',
      items: [
        { id: 'l1',  name: 'Arroz branco',       imageUrl: '/images/foods/arroz.webp',              portion: '4 col. sopa', kcal: 200, protein: 4,  checked: false, alternatives: [] },
        { id: 'l2',  name: 'Feijão',             imageUrl: '/images/foods/feijao.webp',             portion: '1 concha',    kcal: 130, protein: 8,  checked: false, alternatives: [] },
        { id: 'l3',  name: 'Frango grelhado',    imageUrl: '/images/foods/frango.webp',             portion: '150g',        kcal: 250, protein: 45, checked: false, alternatives: [
          { id: 'l3a', name: 'Peito de peru', imageUrl: '/images/foods/frango.webp', portion: '150g', kcal: 220, protein: 42 },
        ]},
        { id: 'l4',  name: 'Carne vermelha',     imageUrl: '/images/foods/carne-vermelha.webp',     portion: '150g',        kcal: 280, protein: 40, checked: false, alternatives: [] },
        { id: 'l5',  name: 'Peixe',              imageUrl: '/images/foods/peixe-assado.webp',       portion: '150g',        kcal: 200, protein: 35, checked: false, alternatives: [] },
        { id: 'l6',  name: 'Salada verde',       imageUrl: '/images/foods/salada-verde.webp',       portion: 'à vontade',   kcal: 40,  protein: 2,  checked: false, alternatives: [] },
        { id: 'l7',  name: 'Batata doce',        imageUrl: '/images/foods/batata-doce.webp',        portion: '100g',        kcal: 90,  protein: 2,  checked: false, alternatives: [] },
        { id: 'l8',  name: 'Farofa',             imageUrl: '/images/foods/farofa.webp',             portion: '2 col. sopa', kcal: 120, protein: 2,  checked: false, alternatives: [] },
        { id: 'l9',  name: 'Cenoura refogada',   imageUrl: '/images/foods/cenoura-refogada.webp',   portion: '3 col. sopa', kcal: 50,  protein: 1,  checked: false, alternatives: [] },
        { id: 'l10', name: 'Brócolis refogado',  imageUrl: '/images/foods/brocolis.webp',           portion: '3 col. sopa', kcal: 55,  protein: 4,  checked: false, alternatives: [] },
        { id: 'l11', name: 'Ovo frito',          imageUrl: '/images/foods/ovo-frito.webp',          portion: '1 unidade',   kcal: 90,  protein: 6,  checked: false, alternatives: [] },
      ],
    },
    {
      id: 'snack',
      name: 'Lanche da tarde',
      shortName: 'Lanche',
      goal: { kcal: 350, protein: 15 },
      streak: 7,
      state: 'open',
      items: [
        { id: 's1', name: 'Fruta (maçã/pera)',      imageUrl: '/images/foods/maca.webp',                    portion: '1 unidade',   kcal: 80,  protein: 1,  checked: false, alternatives: [] },
        { id: 's2', name: 'Iogurte',                imageUrl: '/images/foods/iogurte.webp',                 portion: '1 copo',      kcal: 90,  protein: 8,  checked: false, alternatives: [] },
        { id: 's3', name: 'Sanduíche natural',      imageUrl: '/images/foods/sanduiche-natural.webp',       portion: '1 unidade',   kcal: 250, protein: 12, checked: false, alternatives: [] },
        { id: 's4', name: 'Vitamina de fruta',      imageUrl: '/images/foods/vitaminada.webp',              portion: '1 copo',      kcal: 180, protein: 8,  checked: false, alternatives: [] },
        { id: 's5', name: 'Barrinha de cereal',     imageUrl: '/images/foods/cereal-barra.webp',            portion: '1 unidade',   kcal: 100, protein: 3,  checked: false, alternatives: [] },
        { id: 's6', name: 'Pão de queijo',          imageUrl: '/images/foods/pao-de-queijo.webp',           portion: '2 unidades',  kcal: 150, protein: 4,  checked: false, alternatives: [] },
        { id: 's7', name: 'Café com leite',         imageUrl: '/images/foods/cafe-com-leite.webp',          portion: '1 xícara',    kcal: 60,  protein: 3,  checked: false, alternatives: [] },
        { id: 's8', name: 'Torrada com queijo',     imageUrl: '/images/foods/torrada-com-queijo-branco.webp', portion: '2 fatias',  kcal: 140, protein: 6,  checked: false, alternatives: [] },
        { id: 's9', name: 'Bolacha de água e sal',  imageUrl: '/images/foods/bolacha-de-agua-e-sal.webp',   portion: '5 unidades',  kcal: 130, protein: 3,  checked: false, alternatives: [] },
      ],
    },
    {
      id: 'dinner',
      name: 'Jantar',
      shortName: 'Jantar',
      goal: { kcal: 600, protein: 40 },
      streak: 8,
      state: 'open',
      items: [
        { id: 'd1',  name: 'Frango grelhado',        imageUrl: '/images/foods/frango.webp',                            portion: '150g',       kcal: 250, protein: 45, checked: false, alternatives: [] },
        { id: 'd2',  name: 'Peixe assado',           imageUrl: '/images/foods/peixe-assado.webp',                      portion: '150g',       kcal: 200, protein: 35, checked: false, alternatives: [] },
        { id: 'd3',  name: 'Omelete',                imageUrl: '/images/foods/omelete.webp',                           portion: '1 unidade',  kcal: 200, protein: 18, checked: false, alternatives: [] },
        { id: 'd4',  name: 'Salada',                 imageUrl: '/images/foods/salada-verde.webp',                      portion: 'à vontade',  kcal: 50,  protein: 3,  checked: false, alternatives: [] },
        { id: 'd5',  name: 'Salada + proteína',      imageUrl: '/images/foods/salada-verde.webp',                      portion: '1 prato',    kcal: 300, protein: 30, checked: false, alternatives: [] },
        { id: 'd6',  name: 'Arroz integral',         imageUrl: '/images/foods/arroz.webp',                             portion: '3 col. sopa', kcal: 150, protein: 4, checked: false, alternatives: [] },
        { id: 'd7',  name: 'Purê de batata',         imageUrl: '/images/foods/pure-de-batata.webp',                    portion: '3 col. sopa', kcal: 130, protein: 2, checked: false, alternatives: [] },
        { id: 'd8',  name: 'Tapioca recheada/wrap',  imageUrl: '/images/foods/tapioca-recheada-com-queijo-e-banana.webp', portion: '1 unidade', kcal: 280, protein: 18, checked: false, alternatives: [] },
        { id: 'd9',  name: 'Legumes refogados',      imageUrl: '/images/foods/legumes-refogados.webp',                 portion: '3 col. sopa', kcal: 70,  protein: 3, checked: false, alternatives: [] },
        { id: 'd10', name: 'Carne moída',            imageUrl: '/images/foods/carne-moida.webp',                       portion: '100g',       kcal: 200, protein: 26, checked: false, alternatives: [] },
      ],
    },
    {
      id: 'supper',
      name: 'Ceia',
      shortName: 'Ceia',
      goal: { kcal: 200, protein: 15 },
      streak: 5,
      state: 'open',
      items: [
        { id: 'c1',  name: 'Iogurte natural',       imageUrl: '/images/foods/iogurte.webp',                  portion: '1 copo',      kcal: 90,  protein: 8,  checked: false, alternatives: [] },
        { id: 'c2',  name: 'Banana',                imageUrl: '/images/foods/banana.webp',                   portion: '1 unidade',   kcal: 90,  protein: 1,  checked: false, alternatives: [] },
        { id: 'c3',  name: 'Mamão',                 imageUrl: '/images/foods/maca.webp',                     portion: '1 fatia',     kcal: 60,  protein: 1,  checked: false, alternatives: [] },
        { id: 'c4',  name: 'Chá (camomila/erva-doce)', imageUrl: '/images/foods/cafe-com-leite.webp',        portion: '1 xícara',    kcal: 5,   protein: 0,  checked: false, alternatives: [] },
        { id: 'c5',  name: 'Torrada integral',      imageUrl: '/images/foods/torrada-com-queijo-branco.webp', portion: '2 fatias',   kcal: 80,  protein: 3,  checked: false, alternatives: [] },
        { id: 'c6',  name: 'Queijo branco',         imageUrl: '/images/foods/queijo-branco.webp',            portion: '2 fatias',    kcal: 100, protein: 8,  checked: false, alternatives: [] },
        { id: 'c7',  name: 'Ovo cozido',            imageUrl: '/images/foods/ovo-cozido.webp',               portion: '1 unidade',   kcal: 70,  protein: 6,  checked: false, alternatives: [] },
        { id: 'c8',  name: 'Mingau de aveia',       imageUrl: '/images/foods/mingal-de-aveia.webp',          portion: '1 tigela',    kcal: 150, protein: 5,  checked: false, alternatives: [] },
        { id: 'c9',  name: 'Leite morno',           imageUrl: '/images/foods/leite-morno.webp',              portion: '1 copo',      kcal: 120, protein: 8,  checked: false, alternatives: [] },
        { id: 'c10', name: 'Whey / shake proteico', imageUrl: '/images/foods/vitaminada-leve.webp',          portion: '1 scoop',     kcal: 120, protein: 25, checked: false, alternatives: [] },
        { id: 'c11', name: 'Vitamina leve',         imageUrl: '/images/foods/vitaminada-leve.webp',          portion: '1 copo',      kcal: 130, protein: 6,  checked: false, alternatives: [] },
      ],
    },
    {
      id: 'bonus',
      name: 'Bônus',
      shortName: 'Bônus',
      goal: { kcal: 200, protein: 5 },
      streak: 0,
      state: 'locked',
      items: [
        { id: 'x1',  name: 'Maçã',            imageUrl: '/images/foods/maca.webp',              portion: '1 unidade', kcal: 80, protein: 1, checked: false, alternatives: [] },
        { id: 'x2',  name: 'Banana',          imageUrl: '/images/foods/banana.webp',            portion: '1 unidade', kcal: 90, protein: 1, checked: false, alternatives: [] },
        { id: 'x3',  name: 'Mamão',           imageUrl: '/images/foods/maca.webp',              portion: '1 fatia',   kcal: 60, protein: 1, checked: false, alternatives: [] },
        { id: 'x4',  name: 'Laranja',         imageUrl: '/images/foods/laranja.webp',           portion: '1 unidade', kcal: 70, protein: 1, checked: false, alternatives: [] },
        { id: 'x5',  name: 'Melancia',        imageUrl: '/images/foods/melancia.webp',          portion: '1 fatia',   kcal: 50, protein: 1, checked: false, alternatives: [] },
        { id: 'x6',  name: 'Pepino',          imageUrl: '/images/foods/salada-verde.webp',      portion: '1 unidade', kcal: 30, protein: 1, checked: false, alternatives: [] },
        { id: 'x7',  name: 'Água de coco',    imageUrl: '/images/foods/agua-de-coco.webp',      portion: '1 copo',    kcal: 60, protein: 1, checked: false, alternatives: [] },
        { id: 'x8',  name: 'Castanha-do-pará', imageUrl: '/images/foods/farofa.webp',           portion: '3 unid.',   kcal: 100, protein: 2, checked: false, alternatives: [] },
        { id: 'x9',  name: 'Uva',             imageUrl: '/images/foods/uva.webp',               portion: '1 cacho',   kcal: 80, protein: 1, checked: false, alternatives: [] },
        { id: 'x10', name: 'Batata doce',     imageUrl: '/images/foods/batata-doce.webp',       portion: '100g',      kcal: 90, protein: 2, checked: false, alternatives: [] },
      ],
    },
  ],
}
